CREATE TABLE GROUP_INFORMATION (
	UNIQUE_ID INT AUTO_INCREMENT NOT NULL,
	GROUP_ID VARCHAR(35),
	PASS VARCHAR(5),
	PRIMARY KEY (UNIQUE_ID)
);

ALTER TABLE GROUP_INFORMATION
	AUTO_INCREMENT = 1000 ;

CREATE TABLE BOT_FUNCTION (
	FUNCTION_ID INT AUTO_INCREMENT NOT NULL,
	FUNCTION_NAME VARCHAR(20),
	DESCRIPTION VARCHAR(256),
	PRIMARY KEY (FUNCTION_ID)
);

ALTER TABLE BOT_FUNCTION
	AUTO_INCREMENT = 1 ;

CREATE TABLE GROUP_FUNCTION (
	GF_ID INT AUTO_INCREMENT NOT NULL,
	UNIQUE_ID INT,
	ID_FUNCTION INT,
	KEYWORD VARCHAR(50),
	PRIMARY KEY(GF_ID),
	CONSTRAINT FKGI FOREIGN KEY(UNIQUE_ID) REFERENCES GROUP_INFORMATION(UNIQUE_ID),
	CONSTRAINT FKBF FOREIGN KEY(ID_FUNCTION) REFERENCES BOT_FUNCTION(FUNCTION_ID)
);

ALTER TABLE GROUP_FUNCTION
	AUTO_INCREMENT = 1000 ;

CREATE TABLE LINKED_ACC (
	LINKED_ID INT AUTO_INCREMENT NOT NULL,
	PERSONAL_ID VARCHAR(35),
	GF_ID INT,
	PRIMARY KEY(LINKED_ID),
	CONSTRAINT FKGF FOREIGN KEY(GF_ID) REFERENCES GROUP_FUNCTION(GF_ID)
);

ALTER TABLE LINKED_ACC
	AUTO_INCREMENT = 1000 ;
